#! /usr/bin/env bash

set -euo pipefail
export FLASK_APP=webapp.app

activate() {
    # Create or activate virtualenv
    if [ ! -d ./.venv ]; then
        python3 -m venv .venv
        . ./.venv/bin/activate
        pip install --no-cache-dir -r requirements.txt
    else
        . ./.venv/bin/activate
    fi
}

{
    activate

    # Provision database
    # ===
    flask db upgrade

    RUN_COMMAND="gunicorn webapp.app:app --name $(hostname) --workers=2 --bind $1"

    if [ -z ${FLASK_DEBUG+x} ]; then
        RUN_COMMAND="${RUN_COMMAND} --reload --log-level debug --timeout 9999"
    fi

    ${RUN_COMMAND}
}
