# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    desc: "Start the project"
    cmds:
      - docker compose up -d

  stop:
    desc: "Stop the project"
    cmds:
      - docker compose down

  cleanup:
    desc: "Stop containers and remove volumes"
    cmds:
      - docker compose down -v

  rebuild:
    desc: "Rebuild the project. Only run this if you have made changes to the Docker related files (Dockerfile, docker-compose.yaml)."
    cmds:
      - docker compose up -d --build

  build:
    desc: "Build the project"
    cmds:
      - docker exec cscanonicalcom-web-1 yarn build

  lint:
    desc: "Run linters"
    cmds:
      - docker exec cscanonicalcom-web-1 yarn lint
      - task: lint-python

  lint-python:
    desc: "Run Python linters"
    cmds:
      - docker exec cscanonicalcom-web-1 yarn lint-python

  format-python:
    desc: "Format Python code"
    cmds:
      - docker exec cscanonicalcom-web-1 yarn format-python

  test:
    desc: "Run tests"
    cmds:
      - docker exec cscanonicalcom-web-1 yarn test

  test-e2e:
    desc: "Run playwright e2e tests"
    cmds:
      - docker exec cscanonicalcom-web-1 yarn playwright install
      - docker exec cscanonicalcom-web-1 yarn test-e2e
