export const ENDPOINTS = {
  getPagesTree: (domain: string, noCache?: boolean) => `/api/get-tree/${domain}/${noCache ? "/True" : ""}`,
  getUsers: (inputStr: string) => `/api/get-users/${inputStr}`,
  getTeams: "/api/get-teams",
  setOwner: "/api/set-owner",
  setReviewers: "/api/set-reviewers",
  createNewPage: "/api/create-page",
  requestChanges: "/api/request-changes",
  requestRemoval: "/api/request-removal",
  currentUser: "/api/current-user",
  getProducts: "/api/get-products",
  setProducts: "/api/set-product",
  crudProduct: "/api/product",
  updatePageDetails: "/api/update-page-details",
  getWebpageAssets: "/api/get-webpage-assets",
  reportBug: "/api/report-bug",
  requestFeature: "/api/request-feature",
  getTickets: "/api/tickets",
  getWebpageStats: "/api/get-webpage-stats",
  getJiraProjects: "/api/get-jira-projects",
  submitForContentReview: "/api/submit-for-content-review",
};

export const REST_TYPES = {
  GET: "get",
  POST: "post",
  PUT: "put",
  DELETE: "delete",
  PATCH: "patch",
};
