domain: cs.canonical.com

image: prod-comms.ps5.docker-registry.canonical.com/cs.canonical.com

env:
  - name: REDIS_HOST
    secretKeyRef:
      key: host
      name: webteam-valkey

  - name: REDIS_PORT
    secretKeyRef:
      key: port
      name: webteam-valkey

  - name: GH_TOKEN
    secretKeyRef:
      key: github
      name: webteam-valkey

  - name: DIRECTORY_API_TOKEN
    secretKeyRef:
      key: token
      name: directory-api

  - name: JIRA_EMAIL
    secretKeyRef:
      key: jira-email
      name: cs-canonical-com

  - name: JIRA_TOKEN
    secretKeyRef:
      key: jira-token
      name: cs-canonical-com

  - name: JIRA_URL
    value: "https://warthogs.atlassian.net"

  - name: JIRA_LABELS
    value: "sites_BAU"

  - name: JIRA_COPY_UPDATES_EPIC
    value: "WD-12643"

  - name: GOOGLE_DRIVE_FOLDER_ID
    secretKeyRef:
      key: google-drive-folder-id
      name: cs-canonical-com

  - name: COPYDOC_TEMPLATE_ID
    secretKeyRef:
      key: copydoc-template-id
      name: cs-canonical-com

  - name: GOOGLE_PRIVATE_KEY
    secretKeyRef:
      key: google-private-key
      name: cs-canonical-com
  
  - name: GOOGLE_PRIVATE_KEY_ID
    secretKeyRef:
      key: google-private-key-id
      name: cs-canonical-com

  - name: SITES_MAINTENANCE_EPIC
    value: "WD-21938"

  - name: SITES_MAINTENANCE_LABELS
    value: "sites_Maintenance"

  - name: SITES_NEW_FEATURES_LABELS
    value: "sites_NewFeature"

# Overrides for production
production:
  replicas: 3
  memoryLimit: 512Mi
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
  env:
    - name: DATABASE_URL
      secretKeyRef:
        key: websites-content-system
        name: database-urls

# Overrides for staging
staging:
  replicas: 3
  memoryLimit: 512Mi
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
  env:
    - name: DATABASE_URL
      secretKeyRef:
        key: websites-content-system
        name: database-urls

# Overrides for demos
demo:
  env:
    - name: REDIS_HOST
      secretKeyRef:
        key: host
        name: webteam-valkey

    - name: REDIS_PORT
      secretKeyRef:
        key: port
        name: webteam-valkey

    - name: GH_TOKEN
      secretKeyRef:
        key: github
        name: webteam-valkey

    - name: DIRECTORY_API_TOKEN
      secretKeyRef:
        key: token
        name: directory-api

    - name: JIRA_EMAIL
      secretKeyRef:
        key: jira-email
        name: cs-canonical-com

    - name: JIRA_TOKEN
      secretKeyRef:
        key: jira-token
        name: cs-canonical-com

    - name: JIRA_URL
      value: "https://warthogs.atlassian.net"

    - name: JIRA_LABELS
      value: "sites_BAU"

    - name: JIRA_COPY_UPDATES_EPIC
      value: "WD-12643"

    - name: GOOGLE_DRIVE_FOLDER_ID
      secretKeyRef:
        key: google-drive-folder-id
        name: cs-canonical-com

    - name: COPYDOC_TEMPLATE_ID
      secretKeyRef:
        key: copydoc-template-id
        name: cs-canonical-com

    - name: GOOGLE_PRIVATE_KEY
      secretKeyRef:
        key: google-private-key
        name: cs-canonical-com
    
    - name: GOOGLE_PRIVATE_KEY_ID
      secretKeyRef:
        key: google-private-key-id
        name: cs-canonical-com

    - name: FLASK_DEBUG
      value: "1"

    - name: JIRA_TOKEN
      secretKeyRef:
        key: jira-token
        name: cs-canonical-com

    - name: SITES_MAINTENANCE_EPIC
      value: "WD-21938"

    - name: SITES_MAINTENANCE_LABELS
      value: "sites_Maintenance"

    - name: SITES_NEW_FEATURES_LABELS
      value: "sites_NewFeature"