domain: cs.canonical.com

image: prod-comms.ps5.docker-registry.canonical.com/cs.canonical.com

env:
  - name: VALKEY_HOST
    secretKeyRef:
      key: host
      name: webteam-valkey

  - name: VALKEY_PORT
    secretKeyRef:
      key: port
      name: webteam-valkey

  - name: GH_TOKEN
    secretKeyRef:
      key: github
      name: webteam-valkey

  - name: DIRECTORY_API_TOKEN
    secretKeyRef:
      key: token
      name: directory-api

  - name: JIRA_EMAIL
    secretKeyRef:
      key: jira-email
      name: cs-canonical-com

  - name: JIRA_TOKEN
    secretKeyRef:
      key: jira-token
      name: cs-canonical-com

  - name: JIRA_URL
    value: "https://warthogs.atlassian.net"

  - name: JIRA_LABELS
    value: "sites_BAU"

  - name: JIRA_COPY_UPDATES_EPIC
    value: "WD-12643"

  - name: GOOGLE_DRIVE_FOLDER_ID
    secretKeyRef:
      key: google-drive-folder-id
      name: cs-canonical-com

  - name: COPYDOC_TEMPLATE_ID
    secretKeyRef:
      key: copydoc-template-id
      name: cs-canonical-com

  - name: GOOGLE_PRIVATE_KEY
    secretKeyRef:
      key: google-private-key
      name: cs-canonical-com
  
  - name: GOOGLE_PRIVATE_KEY_ID
    secretKeyRef:
      key: google-private-key-id
      name: cs-canonical-com

# Overrides for production
production:
  replicas: 1
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
  env:
    - name: DATABASE_URL
      secretKeyRef:
        key: websites-content-system
        name: database-urls
  routes:
    - paths: [/_pgadmin]
      name: cs-canonical-com-pgadmin
      app_name: cs.canonical.com-pgadmin
      image: prod-comms.ps5.docker-registry.canonical.com/pgadmin4:latest
      replicas: 1
      memoryLimit: 512Mi
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              key: pg-admin-email
              name: pgadmin-defaults
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: pg-admin-password
              name: pgadmin-defaults
        - name: SCRIPT_NAME
          value: /_pgadmin
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"
        - name: PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT
          value: "False"
        - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED
          value: "False"

# Overrides for staging
staging:
  replicas: 1
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
  env:
    - name: DATABASE_URL
      secretKeyRef:
        key: websites-content-system
        name: database-urls
  routes:
    - paths: [/_pgadmin]
      name: cs-canonical-com-pgadmin
      app_name: cs.canonical.com-pgadmin
      image: prod-comms.ps5.docker-registry.canonical.com/pgadmin4:latest
      replicas: 1
      memoryLimit: 512Mi
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          secretKeyRef:
            key: pg-admin-email
            name: pgadmin-defaults
        - name: PGADMIN_DEFAULT_PASSWORD
          secretKeyRef:
            key: pg-admin-password
            name: pgadmin-defaults
        - name: SCRIPT_NAME
          value: /_pgadmin
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"
        - name: PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT
          value: "False"
        - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED
          value: "False"

# Overrides for demos
demo:
  env:
    - name: VALKEY_HOST
      secretKeyRef:
        key: host
        name: webteam-valkey

    - name: VALKEY_PORT
      secretKeyRef:
        key: port
        name: webteam-valkey

    - name: GH_TOKEN
      secretKeyRef:
        key: github
        name: webteam-valkey

    - name: DIRECTORY_API_TOKEN
      secretKeyRef:
        key: token
        name: directory-api

    - name: JIRA_EMAIL
      secretKeyRef:
        key: jira-email
        name: cs-canonical-com

    - name: JIRA_TOKEN
      secretKeyRef:
        key: jira-token
        name: cs-canonical-com

    - name: JIRA_URL
      value: "https://warthogs.atlassian.net"

    - name: JIRA_LABELS
      value: "sites_BAU"

    - name: JIRA_COPY_UPDATES_EPIC
      value: "WD-12643"

    - name: GOOGLE_DRIVE_FOLDER_ID
      secretKeyRef:
        key: google-drive-folder-id
        name: cs-canonical-com

    - name: COPYDOC_TEMPLATE_ID
      secretKeyRef:
        key: copydoc-template-id
        name: cs-canonical-com

    - name: GOOGLE_PRIVATE_KEY
      secretKeyRef:
        key: google-private-key
        name: cs-canonical-com
    
    - name: GOOGLE_PRIVATE_KEY_ID
      secretKeyRef:
        key: google-private-key-id
        name: cs-canonical-com