domain: cs.canonical.com

image: prod-comms.ps5.docker-registry.canonical.com/cs.canonical.com

env:
  - name: VALKEY_HOST
    secretKeyRef:
      key: host
      name: webteam-valkey

  - name: VALKEY_PORT
    secretKeyRef:
      key: port
      name: webteam-valkey

  - name: GH_TOKEN
    secretKeyRef:
      key: github
      name: webteam-valkey

  - name: SECRET_KEY
    secretKeyRef:
      key: websites-content-system
      name: secret-keys

# Overrides for production
production:
  replicas: 1
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 1
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";