"""
add assets table and webpage_assets table
add file_path column to webpages table

Revision ID: 1b6109065dba
Revises: 1d1c609b8c23
Create Date: 2025-08-13 11:12:52.157695

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b6109065dba"
down_revision = "1d1c609b8c23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "webpage_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("webpage_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["webpage_id"],
            ["webpages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "webpages", sa.Column("file_path", sa.String(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webpages", "file_path")
    op.drop_table("webpage_assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
