"""empty message

Revision ID: 3d5b62292e65
Revises: 68ab742ccfbe
Create Date: 2025-08-12 17:46:09.722844

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d5b62292e65"
down_revision = "68ab742ccfbe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webpage_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("webpage_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["webpage_id"],
            ["webpages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webpage_assets")
    # ### end Alembic commands ###
