"""empty message

Revision ID: 636e244e00ea
Revises: 2cebdd533a59
Create Date: 2025-01-14 13:24:12.886395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636e244e00ea'
down_revision = '2cebdd533a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('webpage_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webpage_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['webpage_id'], ['webpages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webpage_products')
    op.drop_table('products')
    # ### end Alembic commands ###
