"""add assets table

Revision ID: edb49aee1ab4
Revises: 1d1c609b8c23
Create Date: 2025-08-12 07:22:58.312967

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edb49aee1ab4"
down_revision = "1d1c609b8c23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("webpage_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["webpage_id"],
            ["webpages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assets")
    # ### end Alembic commands ###
