name: Pack Charm

on:
  push:
    branches:
      - test-deploy
      - main

env:
  CHARMCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: true
  ROCKCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: true

jobs:
  pack-charm:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files in the charm folder
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files: charm/*

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Setup Charmcraft
        run: sudo snap install charmcraft --classic --channel=latest/edge

      - name: Pack charm
        run: charmcraft pack -v --project-dir ./charm

      - name: Upload charm
        uses: actions/upload-artifact@v4
        with:
          name: cs-canonical-com-charm
          path: ./*.charm
