name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - playwright-tests
jobs:
  run-playwright:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    services:
      valkey:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Install node dependencies
        run: yarn
      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag websites-content-system .
      - name: Run image
        env:
          DISABLE_SSO: True
          SECRET_KEY: secret_key
          VALKEY_HOST: localhost
          VALKEY_PORT: 6379
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_ORG: https://github.com/canonical
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          GOOGLE_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          GOOGLE_PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: https://warthogs.atlassian.net
          JIRA_LABELS: somelabel
          JIRA_COPY_UPDATES_EPIC: WD-12643
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          COPYDOC_TEMPLATE_ID: ${{ secrets.COPYDOC_TEMPLATE_ID }}
          JIRA_REPORTER_ID: ${{ secrets.JIRA_REPORTER_ID }}
        run: |
          docker run -d \
          -p 8104:8104 \
          -e SECRET_KEY="$SECRET_KEY" \
          -e VALKEY_HOST="$VALKEY_HOST" \
          -e VALKEY_PORT="$VALKEY_PORT" \
          -e GH_TOKEN="$GH_TOKEN" \
          -e REPO_ORG="$REPO_ORG" \
          -e DATABASE_URL="$DATABASE_URL" \
          -e GOOGLE_PRIVATE_KEY="$GOOGLE_PRIVATE_KEY" \
          -e GOOGLE_PRIVATE_KEY_ID="$GOOGLE_PRIVATE_KEY_ID" \
          -e JIRA_EMAIL="$JIRA_EMAIL" \
          -e JIRA_TOKEN="$JIRA_TOKEN" \
          -e JIRA_URL="$JIRA_URL" \
          -e JIRA_LABELS="$JIRA_LABELS" \
          -e JIRA_COPY_UPDATES_EPIC="$JIRA_COPY_UPDATES_EPIC" \
          -e GOOGLE_DRIVE_FOLDER_ID="$GOOGLE_DRIVE_FOLDER_ID" \
          -e COPYDOC_TEMPLATE_ID="$COPYDOC_TEMPLATE_ID" \
          -e JIRA_REPORTER_ID="$JIRA_REPORTER_ID" \
          -e DISABLE_SSO="$DISABLE_SSO" \
          -e FLASK_DEBUG=True --network host websites-content-system &
          curl --head --fail --retry-delay 1 --retry 50 --retry-connrefused http://localhost
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          JIRA_REPORTER_ID: ${{ secrets.JIRA_REPORTER_ID }}
        run: |
          JIRA_REPORTER_ID="$JIRA_REPORTER_ID" yarn playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
