name: Playwright Tests

env:
  DISABLE_SSO: True
  SECRET_KEY: secret_key
  VALKEY_HOST: localhost
  VALKEY_PORT: 6379
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_ORG: https://github.com/canonical
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
  GOOGLE_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  GOOGLE_PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
  JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
  JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
  JIRA_URL: https://example.atlassian.net
  JIRA_LABELS: somelabel
  JIRA_COPY_UPDATES_EPIC: WD-12643
  GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
  COPYDOC_TEMPLATE_ID: ${{ secrets.COPYDOC_TEMPLATE_ID }}
  JIRA_REPORTER_ID: ${{ secrets.JIRA_REPORTER_ID }}

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - playwright-tests
jobs:
  run-playwright:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    services:
      valkey:
        image: valkey/valkey
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install node dependencies
        run: yarn
      - name: Install dotrun
        run: sudo pip3 install dotrun requests==2.31.0 # requests version is pinned to avoid breaking changes, can be removed once issue is resolved: https://github.com/docker/docker-py/issues/3256resolved: https://github.com/docker/docker-py/issues/3256
      - name: Install dependencies
        run: |
          sudo chmod -R 777 .
          dotrun install
      - name: Build assets
        run: dotrun build
      - name: Run dotrun
        run: |
          dotrun -e DISABLE_SSO=True &
          curl --head --fail --retry-delay 1 --retry 50 --retry-connrefused http://localhost:8104
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          yarn playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
